# This is required to make rubocop work. Unclear why, but I'm guessing it's because we are disabling cops from that
# gem so we need to require it.
require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

inherit_gem:
  foobara-rubocop-rules:
    - rules/*

Naming/FileName:
  inherit_mode:
    merge:
      - Exclude

Rails/EnvironmentVariableAccess:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
